name: Tests
on: [push, pull_request]
jobs:
  lint:
    name: Lint test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm install
      - run: npm run lint:test
  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16  

      - run: npm install
      - run: npm run build   
